### ISSUE TITLE
使用npm run build的时候出错

### ISSUE THREAD

**Issue by lixinzai** [NolanGit/PersonalHomepage#15]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
然后报错code1

**Comment by NolanGit** [comment]
hi，这个看起来并不是由于项目bug导致的，而是打包时是内存不足引起的，可以查一下这个问题，会有一些调高内存限制的解决方式

**Comment by lixinzai** [comment]
现在是打包成功，但是在访问页面时会有3个错误框，开发者模式下显示userinfo404 searchengines404 get404

**Comment by NolanGit** [comment]
@lixinzai hi，听起来像是没使用python3 run.py启动后端服务？方便附上操作步骤嘛？我这边自测是没有问题的

**Comment by NolanGit** [comment]
哦，也有可能是没有执行初始化sql导致的。您试着执行一下/backend/init.sql的内容试试呢
