### ISSUE TITLE
配置有点多

### ISSUE THREAD

**Issue by willbeee** [NolanGit/PersonalHomepage#18]
邮箱、微信通知那写可不可以可选配置，还有mysql 必须本地吗。

**Comment by NolanGit** [comment]
> 邮箱、微信通知那写可不可以可选配置，还有mysql 必须本地吗。

hi，will：

1. 邮箱和微信是可以不写或者瞎写的，只会影响到推送通知的功能，后期我会做一个文字提示到初始化脚本里。
2. mysql也可以是远端，请修改“PersonalHomepage/blob/master/backend/app/model/model_function.py:18（运行项目时需要连接）”和“PersonalHomepage/blob/master/start.py:138（运行初始化脚本时需要连接）”的代码，将localhost改为你的远端位置，应该就可以了。

**Comment by willbeee** [comment]
> > 邮箱、微信通知那写可不可以可选配置，还有mysql 必须本地吗。
> 
> hi，will：
> 
> 1. 邮箱和微信是可以不写或者瞎写的，只会影响到推送通知的功能，后期我会做一个文字提示到初始化脚本里。
> 2. mysql也可以是远端，请修改“PersonalHomepage/blob/master/backend/app/model/model_function.py:18（运行项目时需要连接）”和“PersonalHomepage/blob/master/start.py:138（运行初始化脚本时需要连接）”的代码，将localhost改为你的远端位置，应该就可以了。

好的感谢。
