### ISSUE TITLE
无法添加用户删除角色

### ISSUE THREAD

**Issue by Rainforestwind** [NolanGit/PersonalHomepage#22]
添加用户在角色选项提示无数据

删除角色提示错误：[user:id]

**Comment by NolanGit** [comment]
> 添加用户在角色选项提示无数据
> 
> 删除角色提示错误：[user:id]

好，我排查一下，可能是有一些初始化数据忘记写入了

**Comment by NolanGit** [comment]
> 添加用户在角色选项提示无数据
> 
> 删除角色提示错误：[user:id]

确实是bug，已经修复了哈，十分感谢！
