### ISSUE TITLE
新闻等接口出错

### ISSUE THREAD

**Issue by zhangrongwu** [NolanGit/PersonalHomepage#23]
字节大佬果然牛逼

然后我这边部署完成后页面能访问。

1、 /news/get
403
msg
:
"失败！没有权限进行此操作。
在角色admin权限上是配置了的。

2、/cloudDrive/save
500
msg
:
"失败！错误信息：[(1048, "Column 'share_token' cannot be null")]"

3、requirements.txt
translators==4.6.20 改成了 translators==4.2.0

**Comment by zhangrongwu** [comment]
<img width="1416" alt="截屏2021-11-26 下午11 03 33" src="https://user-images.githubusercontent.com/9821205/143599924-0f902d20-8add-4f46-b800-f81f29585472.png">
 if not request.referrer.startswith(DOMAIN_NAME):
            return rsp.refuse(), 403

这一段代码不知道干什么的。 权限加了/news/get 新闻接口能用了，就是这数据是什么情况2020年12月的？？？

**Comment by zhangrongwu** [comment]
找到问题了，爬取文章写入出错。说是没权限。单独运行get_news.py是可以写入的。

**Comment by NolanGit** [comment]
> 字节大佬果然牛逼
> 
> 然后我这边部署完成后页面能访问。
> 
> 1、 /news/get 403 msg : "失败！没有权限进行此操作。 在角色admin权限上是配置了的。
> 
> 2、/cloudDrive/save 500 msg : "失败！错误信息：[(1048, "Column 'share_token' cannot be null")]"
> 
> 3、requirements.txt translators==4.6.20 改成了 translators==4.2.0

第一个问题我本意其实是：因为我这个有部署在公网，我不太懂安全方面的，新闻这个接口还无需登录就能访问，所以权限校验的严格了一些，需要准确的域名才能访问，其实如果不部署公网的话，是可以去掉那一行的，数据的话需要重新配置一下定时任务，才可以刷成最新的。
第二个问题我部署一下看一下哈～

**Comment by NolanGit** [comment]
第二个问题已经更新解决了哈～感谢如此细致入微的使用和测试，后边有问题随时联系我～
